"""Initial migration

Revision ID: dd7a873a1c1d
Revises: 
Create Date: 2026-01-08 18:21:36.404418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7a873a1c1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index('idx_ip_rate_limit', ['ip_address', 'request_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_request_timestamp'), ['request_timestamp'], unique=False)

    op.create_table('contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('formatted_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contexts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contexts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contexts_platform'), ['platform'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_context_sequence', ['context_id', 'sequence_order'], unique=True)
        batch_op.create_index(batch_op.f('ix_messages_context_id'), ['context_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_context_id'))
        batch_op.drop_index('idx_context_sequence')

    op.drop_table('messages')
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contexts_platform'))
        batch_op.drop_index(batch_op.f('ix_contexts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_contexts_created_at'))

    op.drop_table('contexts')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_request_timestamp'))
        batch_op.drop_index(batch_op.f('ix_api_usage_endpoint'))
        batch_op.drop_index('idx_ip_rate_limit')

    op.drop_table('api_usage')
    # ### end Alembic commands ###
